//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consumer.AndyLemonway {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://AndyLemonway/", ConfigurationName="AndyLemonway.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://AndyLemonway/FibonacciService", ReplyAction="*")]
        int FibonacciService(int N);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://AndyLemonway/FibonacciService", ReplyAction="*")]
        System.Threading.Tasks.Task<int> FibonacciServiceAsync(int N);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément Xml de l'espace de noms http://AndyLemonway/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://AndyLemonway/XmlToJsonService", ReplyAction="*")]
        Consumer.AndyLemonway.XmlToJsonServiceResponse XmlToJsonService(Consumer.AndyLemonway.XmlToJsonServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://AndyLemonway/XmlToJsonService", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumer.AndyLemonway.XmlToJsonServiceResponse> XmlToJsonServiceAsync(Consumer.AndyLemonway.XmlToJsonServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJsonService", Namespace="http://AndyLemonway/", Order=0)]
        public Consumer.AndyLemonway.XmlToJsonServiceRequestBody Body;
        
        public XmlToJsonServiceRequest() {
        }
        
        public XmlToJsonServiceRequest(Consumer.AndyLemonway.XmlToJsonServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://AndyLemonway/")]
    public partial class XmlToJsonServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Xml;
        
        public XmlToJsonServiceRequestBody() {
        }
        
        public XmlToJsonServiceRequestBody(string Xml) {
            this.Xml = Xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJsonServiceResponse", Namespace="http://AndyLemonway/", Order=0)]
        public Consumer.AndyLemonway.XmlToJsonServiceResponseBody Body;
        
        public XmlToJsonServiceResponse() {
        }
        
        public XmlToJsonServiceResponse(Consumer.AndyLemonway.XmlToJsonServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://AndyLemonway/")]
    public partial class XmlToJsonServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlToJsonServiceResult;
        
        public XmlToJsonServiceResponseBody() {
        }
        
        public XmlToJsonServiceResponseBody(string XmlToJsonServiceResult) {
            this.XmlToJsonServiceResult = XmlToJsonServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Consumer.AndyLemonway.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Consumer.AndyLemonway.WebService1Soap>, Consumer.AndyLemonway.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int FibonacciService(int N) {
            return base.Channel.FibonacciService(N);
        }
        
        public System.Threading.Tasks.Task<int> FibonacciServiceAsync(int N) {
            return base.Channel.FibonacciServiceAsync(N);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumer.AndyLemonway.XmlToJsonServiceResponse Consumer.AndyLemonway.WebService1Soap.XmlToJsonService(Consumer.AndyLemonway.XmlToJsonServiceRequest request) {
            return base.Channel.XmlToJsonService(request);
        }
        
        public string XmlToJsonService(string Xml) {
            Consumer.AndyLemonway.XmlToJsonServiceRequest inValue = new Consumer.AndyLemonway.XmlToJsonServiceRequest();
            inValue.Body = new Consumer.AndyLemonway.XmlToJsonServiceRequestBody();
            inValue.Body.Xml = Xml;
            Consumer.AndyLemonway.XmlToJsonServiceResponse retVal = ((Consumer.AndyLemonway.WebService1Soap)(this)).XmlToJsonService(inValue);
            return retVal.Body.XmlToJsonServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumer.AndyLemonway.XmlToJsonServiceResponse> Consumer.AndyLemonway.WebService1Soap.XmlToJsonServiceAsync(Consumer.AndyLemonway.XmlToJsonServiceRequest request) {
            return base.Channel.XmlToJsonServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumer.AndyLemonway.XmlToJsonServiceResponse> XmlToJsonServiceAsync(string Xml) {
            Consumer.AndyLemonway.XmlToJsonServiceRequest inValue = new Consumer.AndyLemonway.XmlToJsonServiceRequest();
            inValue.Body = new Consumer.AndyLemonway.XmlToJsonServiceRequestBody();
            inValue.Body.Xml = Xml;
            return ((Consumer.AndyLemonway.WebService1Soap)(this)).XmlToJsonServiceAsync(inValue);
        }
    }
}
